name: V2Ray Config Extractor & Checker

on:
  schedule:
   - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v4

      - name: Checkout Sub-Checker Repository
        uses: actions/checkout@v4
        with:
          repository: arshiacomplus/sub-checker
          path: sub-checker


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          echo "Installing Python packages..."
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          if [ -f sub-checker/requirements.txt ]; then
            pip install -r sub-checker/requirements.txt
          fi

      - name: Run Main Extractor Script
        env:
          SEND_TO_TELEGRAM: true
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: python scripts/main.py

      - name: Commit and Push Results
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A .
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "ðŸ“Š Update V2Ray configs"
            git push

          fi
